version: '3'

services:
  prejournal:
    build:
      context: https://github.com/ylebre/prejournal.git#main
      dockerfile: Dockerfile
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - prejournal-db
  prejournal-db:
    build:
      context: https://github.com/ylebre/prejournal.git#main
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prejournal_test # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 123456 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: prejournal_test # The PostgreSQL default database (automatically created at first launch)
  tikiwiki:
    build:
      context: .
      dockerfile: Dockerfile-tikiwiki
    ports:
      - 8180:80
    expose:
      - 8180
    depends_on:
      - tikiwiki-db
    environment:
      - TIKI_DB_HOST=tikiwiki-db
      - TIKI_DB_USER=tiki
      - TIKI_DB_PASS=wiki
      - TIKI_DB_NAME=tikiwiki
  tikiwiki-db:
    image: mariadb
    environment:
      - MYSQL_USER=tiki
      - MYSQL_PASSWORD=wiki
      - MYSQL_DATABASE=tikiwiki
      - MYSQL_ROOT_PASSWORD=tkwkiiii
    volumes: 
        - ./tiki-db-init:/docker-entrypoint-initdb.d
  timeld-cli:
    image: mldio/timeld-cli
